// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCX4wEiyb4F0z72pba_2AhIOH94eR04NEE",
      authDomain: "plfadminpanel.firebaseapp.com",
      projectId: "plfadminpanel",
      storageBucket: "plfadminpanel.appspot.com",
      messagingSenderId: "977817941000",
      appId: "1:977817941000:web:5449dc03a789cf66368dbd",
      measurementId: "G-4432HJ0Y5F");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQMYrhVEbZ2-0cVOPTJzoCuOU3UPtXwBk',
    appId: '1:555903024095:android:a43c98252d3892e1f2626a',
    messagingSenderId: '555903024095',
    projectId: 'noor-moden-77c6d',
    storageBucket: 'noor-moden-77c6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlO1Ro8FUbfBymbNIXfbbOB62DiuVQmCQ',
    appId: '1:555903024095:ios:428226c10b5a6ec1f2626a',
    messagingSenderId: '555903024095',
    projectId: 'noor-moden-77c6d',
    storageBucket: 'noor-moden-77c6d.appspot.com',
    iosClientId:
        '555903024095-borets13ksnn5n38hhreuci9fggpt5tk.apps.googleusercontent.com',
    iosBundleId: 'com.Azainapps.noorModernAdminPanel',
  );
}
