// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe19B_WMR9MQ_ufnYDwsXl2Uqy0u7lffE',
    appId: '1:598928944880:web:69068cc21502a5db539c35',
    messagingSenderId: '598928944880',
    projectId: 'lms-dashboard-4b4a8',
    authDomain: 'lms-dashboard-4b4a8.firebaseapp.com',
    storageBucket: 'lms-dashboard-4b4a8.appspot.com',
    measurementId: 'G-8Q1Z1T1CG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUaVcFLtKZBW02thq3_S8bnZ-Eo4B9xew',
    appId: '1:598928944880:android:19f38717331d9201539c35',
    messagingSenderId: '598928944880',
    projectId: 'lms-dashboard-4b4a8',
    storageBucket: 'lms-dashboard-4b4a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClPjI6a4Q0Pc4VPgqcH6jcSrAlqKx4YC0',
    appId: '1:598928944880:ios:faa329d62de2869d539c35',
    messagingSenderId: '598928944880',
    projectId: 'lms-dashboard-4b4a8',
    storageBucket: 'lms-dashboard-4b4a8.appspot.com',
    iosClientId: '598928944880-jfte0h7sccrvop8ieihlpu4ghjjughqr.apps.googleusercontent.com',
    iosBundleId: 'com.Azainapps.lmsAdminPanel',
  );
}
