// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDe19B_WMR9MQ_ufnYDwsXl2Uqy0u7lffE",
      authDomain: "lms-dashboard-4b4a8.firebaseapp.com",
      projectId: "lms-dashboard-4b4a8",
      storageBucket: "lms-dashboard-4b4a8.appspot.com",
      messagingSenderId: "598928944880",
      appId: "1:598928944880:web:69068cc21502a5db539c35",
      measurementId: "G-8Q1Z1T1CG3");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQMYrhVEbZ2-0cVOPTJzoCuOU3UPtXwBk',
    appId: '1:555903024095:android:a43c98252d3892e1f2626a',
    messagingSenderId: '555903024095',
    projectId: 'noor-moden-77c6d',
    storageBucket: 'noor-moden-77c6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlO1Ro8FUbfBymbNIXfbbOB62DiuVQmCQ',
    appId: '1:555903024095:ios:428226c10b5a6ec1f2626a',
    messagingSenderId: '555903024095',
    projectId: 'noor-moden-77c6d',
    storageBucket: 'noor-moden-77c6d.appspot.com',
    iosClientId:
        '555903024095-borets13ksnn5n38hhreuci9fggpt5tk.apps.googleusercontent.com',
    iosBundleId: 'com.Azainapps.noorModernAdminPanel',
  );
}
